### ISSUE TITLE
error on localblocklist

### ISSUE THREAD

**Issue by maxbooiii** [Just-Jojo/JojoCogs#55]
### Cog

AdvancedBlacklist

### Details

someone managed to error `[p]localblocklist list`. not entire sure how they managed to do that.

### Discord User Information

MAX#1000

### Traceback details (if applicable)

```py
Traceback (most recent call last):
  File "/home/aina/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/aina/redbot/cogs/CogManager/cogs/advancedblacklist/advanced_blacklist.py", line 165, in local_blocklist_list
    for uid, reason in lbl.items():
AttributeError: 'NoneType' object has no attribute 'items'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/aina/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/aina/redenv/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 832, in invoke
    await super().invoke(ctx)
  File "/home/aina/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1348, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/aina/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/aina/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'items'
```
```


### Reproduction

_No response_

**Comment by Just-Jojo** [comment]
Thanks for the report. I had forgot to return when I sent the empty blacklist message :|
